// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProAdvantages.Db;

namespace ProAdvantages.Migrations
{
    [DbContext(typeof(XPOSTDbContext))]
    partial class XPOSTDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProAdvantages.Models.DeliveryService", b =>
                {
                    b.Property<int>("DSID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeliveryRoute");

                    b.Property<int>("PID");

                    b.Property<string>("Type");

                    b.HasKey("DSID");

                    b.HasIndex("PID");

                    b.ToTable("DeliveryServices");
                });

            modelBuilder.Entity("ProAdvantages.Models.Franchise", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.ToTable("Franchises");
                });

            modelBuilder.Entity("ProAdvantages.Models.Parcel", b =>
                {
                    b.Property<int>("PID");

                    b.Property<DateTime>("DeliveryDate");

                    b.Property<string>("Destination");

                    b.Property<string>("Dimension");

                    b.Property<int>("FID");

                    b.Property<int?>("FranchiseID");

                    b.Property<string>("InsuranceWorth");

                    b.Property<string>("Weight");

                    b.HasKey("PID");

                    b.HasIndex("FranchiseID");

                    b.ToTable("Parcels");
                });

            modelBuilder.Entity("ProAdvantages.Models.DeliveryService", b =>
                {
                    b.HasOne("ProAdvantages.Models.Parcel", "Parcel")
                        .WithMany("DeliveryServices")
                        .HasForeignKey("PID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProAdvantages.Models.Parcel", b =>
                {
                    b.HasOne("ProAdvantages.Models.Franchise", "Franchise")
                        .WithMany("Parcels")
                        .HasForeignKey("FranchiseID");
                });
#pragma warning restore 612, 618
        }
    }
}
